USE gym_management_system;

CREATE TABLE CUSTOMER_COURSE
(
  Id INT AUTO_INCREMENT primary key,
  CustomerId INT,
  CourseId INT,
  FOREIGN KEY (CustomerId) REFERENCES CUSTOMER(Id) ON DELETE CASCADE,
  FOREIGN KEY (CourseId) REFERENCES COURSE(Id) ON DELETE CASCADE
);